/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef DistributedSTO_CONSTANTS_H
#define DistributedSTO_CONSTANTS_H

#include "DistributedSTO_types.h"



class DistributedSTOConstants {
 public:
  DistributedSTOConstants();

};

extern const DistributedSTOConstants g_DistributedSTO_constants;



#endif
