/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "DistributedSTO_constants.h"



const DistributedSTOConstants g_DistributedSTO_constants;

DistributedSTOConstants::DistributedSTOConstants() {
}



