# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


SET(CPACK_ARCHIVE_COMPONENT_INSTALL "ON")
SET(CPACK_BINARY_BUNDLE "")
SET(CPACK_BINARY_CYGWIN "")
SET(CPACK_BINARY_DEB "OFF")
SET(CPACK_BINARY_DRAGNDROP "")
SET(CPACK_BINARY_NSIS "OFF")
SET(CPACK_BINARY_OSXX11 "")
SET(CPACK_BINARY_PACKAGEMAKER "")
SET(CPACK_BINARY_RPM "OFF")
SET(CPACK_BINARY_STGZ "ON")
SET(CPACK_BINARY_TBZ2 "OFF")
SET(CPACK_BINARY_TGZ "ON")
SET(CPACK_BINARY_TZ "ON")
SET(CPACK_BINARY_WIX "")
SET(CPACK_BINARY_ZIP "")
SET(CPACK_CMAKE_GENERATOR "Unix Makefiles")
SET(CPACK_COMPONENTS_ALL "devel;lib")
SET(CPACK_COMPONENT_GROUP_DEVELOPMENT_DESCRIPTION "All of the tools you'll ever need to develop lock-free oriented software with libcds")
SET(CPACK_COMPONENT_GROUP_RUNTIME_DESCRIPTION "Only libcds library for runtime")
SET(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
SET(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
SET(CPACK_COMPONENT_devel_DEPENDS "lib")
SET(CPACK_COMPONENT_devel_DISPLAY_NAME "C++ Headers")
SET(CPACK_COMPONENT_devel_GROUP "Development")
SET(CPACK_COMPONENT_lib_DISPLAY_NAME "Libraries")
SET(CPACK_COMPONENT_lib_GROUP "Runtime")
SET(CPACK_DEBIAN_PACKAGE_CONTROL_EXTRA "/home/tslilyai/Documents/Research/sto/libcds/build/cmake/post_install_script.sh;;/home/tslilyai/Documents/Research/sto/libcds/build/cmake/post_uninstall_script.sh;")
SET(CPACK_DEBIAN_PACKAGE_DEPENDS "boost (>= 1.50)")
SET(CPACK_DEBIAN_PACKAGE_HOMEPAGE "https://github.com/khizmax/libcds")
SET(CPACK_DEB_COMPONENT_INSTALL "ON")
SET(CPACK_GENERATOR "STGZ;TGZ;TZ")
SET(CPACK_INSTALL_CMAKE_PROJECTS "/home/tslilyai/Documents/Research/sto/libcds-release;cds;ALL;/")
SET(CPACK_INSTALL_PREFIX "/usr/local")
SET(CPACK_MODULE_PATH "")
SET(CPACK_NSIS_CONTACT "Max Khizhinsky <libcds-user@lists.sourceforge.net>")
SET(CPACK_NSIS_DISPLAY_NAME "cds")
SET(CPACK_NSIS_DISPLAY_NAME_SET "TRUE")
SET(CPACK_NSIS_ENABLE_UNINSTALL_BEFORE_INSTALL "ON")
SET(CPACK_NSIS_INSTALLER_ICON_CODE "")
SET(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
SET(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
SET(CPACK_NSIS_MODIFY_PATH "ON")
SET(CPACK_NSIS_PACKAGE_NAME "cds")
SET(CPACK_OUTPUT_CONFIG_FILE "/home/tslilyai/Documents/Research/sto/libcds-release/CPackConfig.cmake")
SET(CPACK_PACKAGE_CONTACT "Max Khizhinsky <libcds-user@lists.sourceforge.net>")
SET(CPACK_PACKAGE_DEFAULT_LOCATION "/")
SET(CPACK_PACKAGE_DESCRIPTION_FILE "/home/tslilyai/Documents/Research/sto/libcds/build/cmake/description.txt")
SET(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Library of concurrent data structures")
SET(CPACK_PACKAGE_FILE_NAME "cds-2.2.0-1")
SET(CPACK_PACKAGE_INSTALL_DIRECTORY "cds")
SET(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "cds")
SET(CPACK_PACKAGE_NAME "cds")
SET(CPACK_PACKAGE_RELEASE "1")
SET(CPACK_PACKAGE_RELOCATABLE "true")
SET(CPACK_PACKAGE_VENDOR "Humanity")
SET(CPACK_PACKAGE_VERSION "2.2.0")
SET(CPACK_PACKAGE_VERSION_MAJOR "0")
SET(CPACK_PACKAGE_VERSION_MINOR "1")
SET(CPACK_PACKAGE_VERSION_PATCH "1")
SET(CPACK_RESOURCE_FILE_LICENSE "/usr/share/cmake-2.8/Templates/CPack.GenericLicense.txt")
SET(CPACK_RESOURCE_FILE_README "/usr/share/cmake-2.8/Templates/CPack.GenericDescription.txt")
SET(CPACK_RESOURCE_FILE_WELCOME "/usr/share/cmake-2.8/Templates/CPack.GenericWelcome.txt")
SET(CPACK_RPM_COMPONENT_INSTALL "ON")
SET(CPACK_RPM_EXCLUDE_FROM_AUTO_FILELIST_ADDITION "/usr/local")
SET(CPACK_RPM_PACKAGE_GROUP "System Environment/Base")
SET(CPACK_RPM_PACKAGE_LICENSE "GPL")
SET(CPACK_RPM_PACKAGE_RELEASE "1")
SET(CPACK_RPM_PACKAGE_REQUIRES "boost >= 1.50")
SET(CPACK_RPM_PACKAGE_URL "https://github.com/khizmax/libcds")
SET(CPACK_RPM_POST_INSTALL_SCRIPT_FILE "/home/tslilyai/Documents/Research/sto/libcds/build/cmake/post_install_script.sh")
SET(CPACK_RPM_POST_UNINSTALL_SCRIPT_FILE "/home/tslilyai/Documents/Research/sto/libcds/build/cmake/post_uninstall_script.sh")
SET(CPACK_RPM_devel_PACKAGE_REQUIRES "boost >= 1.50, cds-lib = 2.2.0")
SET(CPACK_SET_DESTDIR "OFF")
SET(CPACK_SOURCE_CYGWIN "")
SET(CPACK_SOURCE_GENERATOR "TGZ;TBZ2;TZ")
SET(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/home/tslilyai/Documents/Research/sto/libcds-release/CPackSourceConfig.cmake")
SET(CPACK_SOURCE_TBZ2 "ON")
SET(CPACK_SOURCE_TGZ "ON")
SET(CPACK_SOURCE_TZ "ON")
SET(CPACK_SOURCE_ZIP "OFF")
SET(CPACK_SYSTEM_NAME "Linux")
SET(CPACK_TOPLEVEL_TAG "Linux")
SET(CPACK_WIX_SIZEOF_VOID_P "8")
